name: main

on:
  push:
    branches: main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        env:
          PACKAGES_USER: ${{ secrets.PACKAGES_USER }}
          PACKAGES_TOKEN: ${{ secrets.PACKAGES_TOKENe }}
        shell: bash
        run: |
          echo $PACKAGES_TOKEN | docker login --username $PACKAGES_USER --password-stdin ghcr.io

      - name: Build tii-fog-drone image and push
        shell: bash
        run: |
          docker build -t gchr.io/kulmesa/tii-fog-drone:latest -f fog-drone/Dockerfile fog-drone/
          docker push gchr.io/kulmesa/tii-fog-drone:latest
