name: main

on:
  push:
    branches: main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.PACKAGES_USER }}
          password: ${{ secrets.PACKAGES_TOKEN }}

      - name: Build tii-fog-drone image and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./fog-drone/
          file: ./fog-drone/Dockerfile
          push: false
          tags: ghcr.io/kulmesa/tii-fog-drone:latest
